version: "3.8"
services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8001:8001
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_air
    # networks:
    #   - baltic_network
  
  mysql_air:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3303 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    # networks:
    #   - baltic_network
volumes:
  my-db:

# networks:
#   baltic_network:
#     name: baltic_network